// <auto-generated />
using System;
using HandCraft.Siparis.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HandCraft.Siparis.Persistence.Migrations
{
    [DbContext(typeof(SiparisDbContext))]
    [Migration("20260607150229_SiparisDurumEklendi")]
    partial class SiparisDurumEklendi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HandCraft.Siparis.Domain.Entities.Siparis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ToplamTutar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Siparisler", (string)null);
                });

            modelBuilder.Entity("HandCraft.Siparis.Domain.Entities.SiparisUrunBilgi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Adet")
                        .HasColumnType("int");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SiparisId")
                        .HasColumnType("int");

                    b.Property<string>("UrunAdi")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("UrunId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("SiparisId");

                    b.ToTable("SiparisUrunBilgileri", (string)null);
                });

            modelBuilder.Entity("HandCraft.Siparis.Domain.Entities.Siparis", b =>
                {
                    b.OwnsOne("HandCraft.Siparis.Domain.Entities.Address", "Adres", b1 =>
                        {
                            b1.Property<int>("SiparisId")
                                .HasColumnType("int");

                            b1.Property<string>("AcikAdres")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("AcikAdres");

                            b1.Property<string>("Il")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Il");

                            b1.Property<string>("Ilce")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Ilce");

                            b1.HasKey("SiparisId");

                            b1.ToTable("Siparisler");

                            b1.WithOwner()
                                .HasForeignKey("SiparisId");
                        });

                    b.Navigation("Adres")
                        .IsRequired();
                });

            modelBuilder.Entity("HandCraft.Siparis.Domain.Entities.SiparisUrunBilgi", b =>
                {
                    b.HasOne("HandCraft.Siparis.Domain.Entities.Siparis", null)
                        .WithMany("Urunler")
                        .HasForeignKey("SiparisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HandCraft.Siparis.Domain.Entities.Siparis", b =>
                {
                    b.Navigation("Urunler");
                });
#pragma warning restore 612, 618
        }
    }
}
